language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - php: 'nightly'
      install:
         - composer install --no-interaction --ignore-platform-reqs
      env: IGNORE_PLATFORM_REQS=true
    - php: '7.4'
      name: 'Prefer lowest'
      install:
         - composer install --no-interaction
         - composer update --prefer-lowest
    - php: '7.4'
      name: 'No video-tools and no ffmpeg'
      install:
        - composer remove --dev --no-interaction datagutten/video-tools
  allow_failures:
    - php: 'nightly'

addons:
 apt:
  packages:
   - ffmpeg

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files

install:
    composer install --no-interaction

before_script:
 - echo 'date.timezone = "Europe/Oslo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit
