language: php

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
    - php: 'nightly'
      install:
         - composer install --no-interaction --ignore-platform-reqs
      env: IGNORE_PLATFORM_REQS=true
    - php: '7.4'
      name: 'Prefer lowest'
      install:
         - composer install --no-interaction
         - composer update --prefer-lowest
    - php: '7.4'
      name: 'No ffmpeg'
      addons:
        apt:
          packages:
            - php-xml
    - php: '7.4'
      name: 'No video-tools and no ffmpeg'
      addons:
        apt:
          packages:
            - php-xml
      install:
        - composer remove --dev --no-interaction datagutten/video-tools
  allow_failures:
    - php: 'nightly'

addons:
 apt:
  packages:
   - php-xml
   - ffmpeg

install:
    composer install --no-interaction

before_script:
 - echo 'date.timezone = "Europe/Oslo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)